# -*- coding: utf-8 -*-
import pathlib

content = """# MA TRẬN CHUYỂN DỊCH NỘI DUNG CHƯƠNG 3 (CH3 REDESIGN CONTENT MIGRATION MAP R4)

- **Cổng trạng thái:** `R3_0_REVISE_BLOCKING / PENDING_R4_INDEPENDENT_REVIEW` (Chờ thẩm định độc lập R4; chưa mở R3-1).
- **Phiên bản tài liệu:** `Revision R4` (Hiệu chỉnh toàn diện theo yêu cầu R3-0 R4, trích xuất máy 53 hàng bảng thật từ `CHAPTER_3_DRAFT_R2.md`, lập Bảng kiểm kê nguồn xác lập mẫu số định lượng 79 mục [53 hàng bảng + 26 khối fact văn bản], chuẩn hóa độc lập schema Bảng 3.5, audit toàn bộ ID/locator và ETM-C-02 theo Báo cáo thẩm định độc lập R3 tại `work/do-an/R3_0_EVIDENCE_VISUAL_BLUEPRINT_EXTERNAL_REVIEW_R3.md`).
- **Candidate R3 nguồn:** `baafb388b632ac03d50cf799c18918ad30e4540c`.
- **Tài liệu căn cứ lộ trình:** `work/do-an/ROADMAP_CH3_REDESIGN_EVIDENCE_FIRST_2026_10_07.md`.
- **Tài liệu kiến trúc cơ sở:** `work/do-an/CH3_REDESIGN_EVIDENCE_VISUAL_BLUEPRINT_R1.md` (Revision R4).
- **Sổ đăng ký bảng/hình:** `work/do-an/CH3_REDESIGN_TABLE_FIGURE_LEDGER_R1.md` (Revision R4).
- **Bản thảo nguồn cần chuyển dịch:** `work/do-an/CHAPTER_3_DRAFT_R2.md` (Git blob `40d2a895bc970f88d7260b3138b8a701f5eb0a8c`; phương pháp đếm dòng được khai báo minh bạch: 317 dòng văn bản nội dung theo `Get-Content`/Python `splitlines()` và 318 dòng khi hiển thị kèm ký tự xuống dòng cuối tệp `\\n`).
- **Nhánh làm việc canonical:** `feature/ch3-redesign-evidence-first-r1`.
- **Commit khởi tạo lộ trình:** `170aa24293b2cf8e579abb1ecf60920bca418bd9`.
- **Mục tiêu tài liệu:** Thiết lập bản đồ chuyển dịch từng khối nội dung (Block-by-Block Migration Map), Bảng kiểm kê nguồn xác lập mẫu số định lượng (Source Inventory & Explicit Denominator) gồm đúng **53 hàng bảng cũ thực tế** và **26 khối dữ kiện văn bản có nghĩa** ($53 + 26 = 79$ mục kiểm kê nguồn), cùng Ma trận truy vết chi tiết từng luận điểm kỹ thuật (Granular Claim Traceability Matrix) từ cấu trúc cũ sang 8 đề mục Chương 3 mới (3.1 đến 3.8); bảo đảm đối soát đầy đủ 100% dữ kiện nguồn (78 mục chuyển dịch + 1 mục retire có lý do $\\to$ 41 claims chuẩn hóa), phân định chính xác cấp độ bằng chứng (78 primary + 5 secondary), bảo tồn nguyên vẹn 5 tiên đề chân lý và ranh giới phương pháp luận.

---

## 1. NGUYÊN TẮC CHUYỂN DỊCH NỘI DUNG (MIGRATION PRINCIPLES)

1. **Bảo tồn chân lý kỹ thuật, tái cấu trúc kiến trúc diễn ngôn:**
   - Việc phê duyệt bản thảo cũ (`CHAPTER_3_DRAFT_R2.md`) bảo vệ tính xác thực của các dữ kiện kỹ thuật (technical truth) và bằng chứng đo đạc; việc người dùng mở lại (reopen) kiến trúc Chương 3 cho phép viết lại cách kể chuyện (narrative) và tổ chức lại các đề mục mà không làm mất đi bất kỳ sự thật khoa học nào.
   - Tuyệt đối cấm tự ý sửa đổi số liệu, địa chỉ IP, cờ giao thức, phiên bản driver, hoặc làm sai lệch kết quả đo đạc. Mọi diễn giải trong tài liệu tổng hợp cũ phải đối chiếu trực tiếp với raw evidence và locks mới hơn.
2. **Khai báo phương pháp đếm dòng và xác lập mẫu số định lượng (Explicit Denominator):**
   - File `CHAPTER_3_DRAFT_R2.md` (blob `40d2a895bc970f88d7260b3138b8a701f5eb0a8c`) gồm 317 dòng nội dung khi đếm bằng lệnh chuẩn PowerShell `(Get-Content CHAPTER_3_DRAFT_R2.md).Count` hoặc hàm Python `splitlines()`. Khi công cụ soạn thảo tính thêm ký tự xuống dòng kết thúc tệp, chỉ số dòng hiển thị là 318 dòng. Cả hai cách đếm phản ánh cùng một tệp nguyên vẹn.
   - Để khắc phục triệt để tồn tại trong các đợt review trước (không tự chọn số mục tổng từ trước hay dùng ước lượng trí nhớ), Revision R4 sử dụng công cụ tự động trích xuất trực tiếp toàn bộ các hàng bảng thật từ `CHAPTER_3_DRAFT_R2.md` (loại bỏ tiêu đề bảng, dòng header và dòng phân cách `---`): kết quả thực tế gồm đúng **53 hàng dữ liệu** (Bảng 3.1: 11 hàng, Bảng 3.2: 7 hàng, Bảng 3.3: 5 hàng, Bảng 3.4: 4 hàng, Bảng 3.5: 8 hàng, Bảng 3.6: 10 hàng, Bảng 3.7: 8 hàng; tổng $11+7+5+4+8+10+8 = 53$). Cùng với **26 khối dữ kiện văn bản có nghĩa** bao trọn toàn bộ nội dung diễn giải từ dòng 1 đến 318, mẫu số định lượng xác lập chính xác là **79 mục kiểm kê nguồn** ($53 + 26 = 79$).
   - Trong 79 mục kiểm kê: **78 mục được chuyển dịch trọn vẹn** (REUSE / MOVE / EXPAND / SYNTHESIZE), và **1 mục duy nhất được retire có lý do** (thời lượng quét 0.51 giây tại dòng 278 do thiếu đồng hồ đo đối chứng độc lập). Toàn bộ 78 mục chuyển dịch được bao trùm hoàn toàn bởi bộ khung **41 luận điểm kỹ thuật chuẩn hóa** (`Claim-01` đến `Claim-41`) trong Ma trận truy vết chi tiết tại Mục 4.
3. **Hệ thống nhãn hành động chuẩn mực (Action Tags):**
   - `REUSE`: Giữ nguyên dữ kiện kỹ thuật và cấu trúc lập luận cốt lõi, tinh chỉnh văn phong cho tự nhiên và chuẩn mực tiếng Việt học thuật.
   - `MOVE`: Chuyển nguyên khối nội dung hoặc bảng biểu sang đề mục mới tương ứng trong cấu trúc 8 phần.
   - `REWRITE`: Viết lại cách diễn đạt, thay đổi góc nhìn từ "nhật ký thực thi lệnh" sang "dẫn dắt câu chuyện khoa học giải đáp câu hỏi của người đọc".
   - `MERGE`: Gộp các đoạn phân mảnh hoặc các kết quả đo tương đồng vào một khối thống nhất để tăng tính liên kết (nêu rõ quan hệ many-to-one).
   - `TRIM`: Lược bỏ các diễn đạt rườm rà, các đoạn lặp lại suy diễn, hoặc các mô tả mang tính liệt kê giao thức không cần thiết.
   - `RETIRE FROM MAIN NARRATIVE`: Đưa các chi tiết bổ trợ hoặc các biến số point-in-time runtime ra khỏi mạch đọc chính (ví dụ thời lượng phiên quét 0.51 giây), lưu giữ đầy đủ ở tầng đối soát và kho bằng chứng bổ trợ (supporting evidence).
4. **Phân cấp bằng chứng staging (83 tệp):**
   - 78 tệp chứng cứ sơ cấp / trực tiếp (`PRIMARY_RAW`, `PRIMARY_VISUAL`, `PRIMARY_LOCAL_STATE`, `PRIMARY_VISUAL_WITH_BOUNDED_CONFLICT`).
   - 5 tệp chứng cứ thứ cấp / siêu dữ liệu (`SECONDARY_META`: 4 tệp run manifest; `SECONDARY_META_CLOSURE`: Section 21 của `RUN4_PAUSE_STATE_REPORT.txt`).

---

## 2. MA TRẬN ÁNH XẠ TỔNG THỂ CÁC ĐỀ MỤC (SECTION-LEVEL MIGRATION)

| Đề mục cấu trúc cũ (Old Sections) | Tên đề mục cũ | Đề mục cấu trúc mới (New Sections) | Tên đề mục mới đề xuất | Chiến lược chuyển dịch chính |
|---|---|---|---|---|
| *Chưa có đề mục tương ứng* | *Nằm rải rác ở lời mở đầu và Chương 2* | **3.1. Mục tiêu và tổ chức thực nghiệm**<br>• 3.1.1. Mục tiêu kiểm chứng<br>• 3.1.2. Luồng thực nghiệm | Mục tiêu kiểm chứng và Luồng thực nghiệm | **NEW & REWRITE**: Xây dựng phần dẫn nhập chiến lược, giải thích rõ mục tiêu kiểm chứng an toàn (không exploit) và sơ đồ luồng hai nhánh độc lập (Hình 3.1 mới). |
| **3.1. Trạng thái baseline trước đo đạc**<br>• 3.1.1. Trạng thái mạng và dịch vụ SMB<br>• 3.1.2. Trạng thái bản vá và mốc phục hồi | Trạng thái baseline trước đo đạc | **3.2. Xác lập trạng thái ban đầu của hệ thống**<br>• 3.2.1. Trạng thái mạng và dịch vụ SMB<br>• 3.2.2. Trạng thái bản vá MS17-010 | Xác lập trạng thái ban đầu của hệ thống | **MOVE & RESTRUCTURE**: Tách bạch rõ ràng giữa trạng thái mạng/dịch vụ (3.2.1) và trạng thái bản vá nội bộ UNPATCHED (3.2.2); tối ưu hóa hình ảnh sang Hình 3.2 và Hình 3.3. Dẫn nguồn Microsoft chính thức S032. |
| **3.2. Kết quả Kịch bản 1 — Khảo sát dịch vụ SMB**<br>• 3.2.1. Khảo sát trạm mạng và trạng thái mở cổng<br>• 3.2.2. Nhận diện phiên bản và đặc tính giao thức | Khảo sát dịch vụ SMB (Kịch bản 1) | **3.3. Khảo sát dịch vụ SMB từ trạm Kali Linux**<br>• 3.3.1. Phát hiện máy chủ và khả năng tiếp cận SMB<br>• 3.3.2. Nhận diện giao thức và các đặc tính SMB<br>• 3.3.3. Tổng hợp kết quả khảo sát | Khảo sát dịch vụ SMB từ trạm Kali Linux | **MOVE & REWRITE**: Tái cấu trúc từ góc nhìn trạm kiểm thử: phát hiện trạm $\\to$ tiếp cận cổng $\\to$ nhận diện phương ngữ $\\to$ tổng hợp bảng dữ liệu (Bảng 3.3). Giữ chi tiết capabilities (DFS, Leasing, Multi-credit) và signing policy. |
| **3.3. Kết quả Kịch bản 2 — Kiểm tra dấu hiệu MS17-010**<br>• 3.3.1. Khảo sát điều kiện kết nối và thuộc tính (NSE01–03)<br>• 3.3.2. Đánh giá dấu hiệu MS17-010 và đối chiếu bản vá (NSE04) | Kiểm tra dấu hiệu MS17-010 (Kịch bản 2) | **3.4. Kiểm tra dấu hiệu MS17-010**<br>• 3.4.1. Kết quả kiểm tra từ xa bằng Nmap/NSE<br>• 3.4.2. Đối chiếu với trạng thái bản vá trên Windows | Kiểm tra dấu hiệu MS17-010 | **MOVE, TRIM & EXPAND**: Tinh giản NSE01–03 làm bối cảnh xác nhận; tập trung phân tích NSE04 (Hình 3.6 UNKNOWN, câu lệnh chuẩn xác không `sudo`, không `unsafe=0`); mở rộng mục 3.4.2 chuyên sâu đối chiếu giữa Remote UNKNOWN và Local UNPATCHED (Hình 3.7 mới). |
| **3.4. Kết quả Case B — Vô hiệu hóa SMBv1**<br>• 3.4.1. Thao tác vô hiệu hóa và kiểm tra cục bộ<br>• 3.4.2. Đo đạc lại từ xa và đối chiếu đa tầng | Vô hiệu hóa SMBv1 (Case B) | **3.5. Thực nghiệm vô hiệu hóa SMBv1 trên máy chủ**<br>• 3.5.1. Trạng thái trước và sau khi vô hiệu hóa SMBv1<br>• 3.5.2. Kết quả kiểm tra lại từ Kali Linux<br>• 3.5.3. Tổng hợp sự thay đổi quan sát được | Thực nghiệm vô hiệu hóa SMBv1 trên máy chủ | **MOVE & RESTRUCTURE**: Tái cấu trúc theo chuỗi hành động trực quan: Trước/Sau nội bộ (3.5.1 với Hình 3.8 3-panel, point-in-time Running) $\\to$ Đo lại từ xa (3.5.2 với Hình 3.9, TCP 139 not remeasured, TCP 445 open không có `--reason`) $\\to$ Bảng tổng hợp thay đổi (3.5.3 với Bảng 3.5 giữ đúng schema đặc thù 8 thuộc tính Case B). |
| **3.5. Kết quả Case C — Kiểm soát SMB bằng pfSense**<br>• 3.5.1. Thiết lập cầu nối và chính sách kiểm soát<br>• 3.5.2. Đo đạc từ xa, đối chiếu nhật ký và trạng thái máy chủ | Kiểm soát SMB bằng pfSense (Case C) | **3.6. Thực nghiệm kiểm soát truy cập SMB bằng pfSense**<br>• 3.6.1. Bố trí pfSense và kiểm soát lưu lượng SMB<br>• 3.6.2. Kết quả kiểm tra lại từ Kali Linux<br>• 3.6.3. Đối chiếu kết quả tại Kali, pfSense và Windows | Thực nghiệm kiểm soát truy cập SMB bằng pfSense | **MOVE & EXPAND**: Sơ đồ kiến trúc Transparent Bridge (Hình 3.10); cấu hình rule order (Hình 3.11); kết quả filtered (Hình 3.12, ghi nhận arp-response); phân tích đối chiếu 3 bên có bảo lưu xung đột nhãn quy tắc CF-11 (Hình 3.13), Windows cuối lượt trỏ Section 21 của `RUN4_PAUSE_STATE_REPORT.txt` (dòng 376–384), LanmanServer Running là truth lock ETM-C-02 kế thừa. |
| **3.6. So sánh kết quả thực nghiệm** | So sánh kết quả thực nghiệm | **3.7. Đối chiếu kết quả các trạng thái thực nghiệm**<br>• 3.7.1. Đối chiếu trạng thái ban đầu và sau các can thiệp<br>• 3.7.2. Những thay đổi và yếu tố không thay đổi | Đối chiếu kết quả các trạng thái thực nghiệm | **MOVE & RESTRUCTURE**: Tách thành 2 tiểu mục: 3.7.1 tập trung vào ma trận dữ liệu Bảng 3.7 (schema riêng 8 tiêu chí tổng hợp 3 trạng thái, Case C dialect ghi NOT MEASURED); 3.7.2 phân định bản chất hai vị trí can thiệp (Host vs. Network Path) qua sơ đồ Hình 3.14 mới. |
| **3.7. Tổng kết chương** | Tổng kết chương | **3.8. Tổng kết chương** | Tổng kết chương | **MOVE & REWRITE**: Viết lại cô đọng, trang trọng, tóm lược 5 phát hiện then chốt và chuyển giao dữ kiện sạch cho Chương 4 thảo luận rủi ro. |

---

## 3. BẢNG KIỂM KÊ NGUỒN CÁC FACT VÀ TỪNG HÀNG BẢNG CŨ (SOURCE INVENTORY & EXPLICIT DENOMINATOR)

Toàn bộ **53 hàng bảng dữ liệu thực tế** (trích xuất tự động bằng công cụ từ 7 bảng cũ) và **26 khối dữ kiện văn bản có nghĩa** trong `CHAPTER_3_DRAFT_R2.md` (tổng cộng **79 mục kiểm kê nguồn**) được lập danh mục chi tiết dưới đây:

### 3.1. Kiểm kê toàn bộ 53 hàng dữ liệu của 7 bảng cũ (Old Tables Row Inventory)

| STT | Source Key | Bảng cũ & Dòng | Nhãn hàng chính xác (Exact Row Label) | Dữ kiện kỹ thuật nguồn | Đích đến cấu trúc mới | Hành động (Action) | Ranh giới / Lý do chuyển dịch |
|---|---|---|---|---|---|---|---|
| 1 | `SRC-TBL-01` | Bảng 3.1, L20 | Địa chỉ IP và mạng con Kali Linux | `192.168.56.10/24` (eth0) | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Môi trường lab Host-Only cô lập. |
| 2 | `SRC-TBL-02` | Bảng 3.1, L21 | Địa chỉ IP và mạng con Windows Server | `192.168.56.20/24` (Ethernet) | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Không default route, không kết nối ngoài. |
| 3 | `SRC-TBL-03` | Bảng 3.1, L22 | Cấu hình card mạng VirtualBox | Host-Only Adapter (`VirtualBox Host-Only Ethernet Adapter`) | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Mạng thuần nội bộ giữa hai máy ảo. |
| 4 | `SRC-TBL-04` | Bảng 3.1, L23 | Dịch vụ chia sẻ tệp (LanmanServer) | `Running`, chế độ khởi động `Automatic` | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Trạng thái dịch vụ cục bộ mốc xuất phát. |
| 5 | `SRC-TBL-05` | Bảng 3.1, L24 | Tính năng Windows FS-SMB1 | Trạng thái `Installed` | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Tính năng hệ điều hành hỗ trợ SMBv1. |
| 6 | `SRC-TBL-06` | Bảng 3.1, L25 | Cấu hình giao thức SMB Server | `EnableSMB1Protocol : True`, `EnableSMB2Protocol : True` | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Cấu hình máy chủ kích hoạt cả hai giao thức. |
| 7 | `SRC-TBL-07` | Bảng 3.1, L26 | Chính sách ký số gói tin SMB nội bộ | `RequireSecuritySignature : False`, `EnableSecuritySignature : False` | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Cờ cấu hình nội bộ; phân biệt với signing từ xa. |
| 8 | `SRC-TBL-08` | Bảng 3.1, L27 | Trạng thái lắng nghe cổng cục bộ | PID 4 lắng nghe TCP 445 (`::`) và TCP 139 (`192.168.56.20`) | Bảng 3.1 (Mục 3.2.1) | `MOVE` | Lắng nghe cục bộ qua `Get-NetTCPConnection`. |
| 9 | `SRC-TBL-09` | Bảng 3.1, L28 | Trạng thái hồ sơ Windows Firewall | `Domain: ON`, `Private: ON`, `Public: ON` | Bảng 3.1 (Mục 3.2.1) | `MOVE & EXPAND` | Tường lửa kích hoạt trên cả 3 hồ sơ. |
| 10 | `SRC-TBL-10` | Bảng 3.1, L29 | Nhóm quy tắc chia sẻ tệp mặc định | Nhóm `File and Printer Sharing (SMB-In)` gồm 16 quy tắc ở trạng thái `False` | Bảng 3.1 (Mục 3.2.1) | `MOVE & EXPAND` | Quy tắc mặc định bị vô hiệu hóa. |
| 11 | `SRC-TBL-11` | Bảng 3.1, L30 | Quy tắc tường lửa tùy biến | Quy tắc `ATTT Lab SMB 139-445` (Inbound, Allow, TCP 139/445, chỉ cho phép `192.168.56.10`) | Bảng 3.1 (Mục 3.2.1) | `MOVE & EXPAND` | Chỉ mở cổng cho trạm kiểm thử Kali. |
| 12 | `SRC-TBL-12` | Bảng 3.2, L64 | Chuỗi phiên bản hiển thị tệp `srv.sys` | `6.3.9600.16384` (`winblue_rtm.130821-1623`) | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Chuỗi hiển thị tệp, không phải số nhị phân so sánh. |
| 13 | `SRC-TBL-13` | Bảng 3.2, L65 | Phiên bản số nhị phân tệp `srv.sys` | `6.3.9600.16421` (ghép FileMajor/Minor/Build/PrivatePart) | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Căn cứ nhị phân chuẩn xác đối chiếu với ngưỡng. |
| 14 | `SRC-TBL-14` | Bảng 3.2, L66 | Ngưỡng phiên bản cập nhật tối thiểu | `6.3.9600.18604` (theo tài liệu Microsoft Support S032) | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Căn cứ thẩm quyền Microsoft chính thức (S032). |
| 15 | `SRC-TBL-15` | Bảng 3.2, L67 | Mã bản vá liên quan khắc phục MS17-010 | `KB4012213` (Security Only) hoặc `KB4012216` (Monthly Rollup) | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Mã gói cập nhật khắc phục lỗ hổng đã biết. |
| 16 | `SRC-TBL-16` | Bảng 3.2, L68 | Danh mục bản vá hệ thống ghi nhận | 6 hotfix năm 2014 (KB2919355..KB2949621); thiếu KB4012213/KB4012216 | Bảng 3.2 (Mục 3.2.2) | `MOVE` | `Get-HotFix` cục bộ chứng minh thiếu bản vá đã biết. Nguồn: `Final_PreDemo_Audit.txt` Section 3. |
| 17 | `SRC-TBL-17` | Bảng 3.2, L69 | Phân loại trạng thái bản vá cục bộ | `UNPATCHED` đối với lỗ hổng MS17-010 | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Diễn giải suy luận dựa trên so sánh $16421 < 18604$. |
| 18 | `SRC-TBL-18` | Bảng 3.2, L70 | Mốc khôi phục môi trường (Snapshot) | `BASE-CLEAN-2026-10-04` (Snapshot Before Demo lúc poweroff) | Bảng 3.2 (Mục 3.2.2) | `MOVE` | Mốc phục hồi kiểm chứng từ `Before_Demo_Snapshots.txt`. |
| 19 | `SRC-TBL-19` | Bảng 3.3, L96 | **B2 — Phát hiện trạm mạng** | Quét Nmap Ping sweep (`-sn`): 4 IP trực tuyến (.1, .10, .20, .100) | Bảng 3.3 (Mục 3.3.3) | `MOVE` | Trạm `.56.100` mang nhãn bắt buộc UNKNOWN identity. |
| 20 | `SRC-TBL-20` | Bảng 3.3, L97 | **B3 — Kiểm tra mục tiêu trực tuyến** | Nmap ARP đơn điểm (`-sn -PR`): `Host is up (0.00037s latency)`, MAC `08:00:27:0B:DA:B7` | Bảng 3.3 (Mục 3.3.3) | `MOVE` | Xác định mục tiêu trực tuyến qua ARP đơn điểm (Layer 2), không phải Ping/Layer 3. |
| 21 | `SRC-TBL-21` | Bảng 3.3, L98 | **B4 — Khảo sát cổng dịch vụ SMB** | Nmap SYN scan (`-sS -p 139,445 --reason`): TCP 139/445 `open syn-ack ttl 128` | Bảng 3.3 (Mục 3.3.3) | `MOVE` | Cổng mở tiếp nhận kết nối. Tiên đề: `445 OPEN != vulnerable`. |
| 22 | `SRC-TBL-22` | Bảng 3.3, L99 | **B5 — Nhận diện phiên bản dịch vụ** | Nmap `-sV`: 139 netbios-ssn, 445 microsoft-ds; OS `Windows Server 2008 R2 - 2012` | Bảng 3.3 (Mục 3.3.3) | `MOVE` | Dải fingerprint nhận diện từ xa; không định danh tuyệt đối. |
| 23 | `SRC-TBL-23` | Bảng 3.3, L100 | **B6 — Phân tích đặc tính giao thức SMB** | 5 dialect NT LM 0.12..3.0.2; capabilities DFS/Leasing/Multi-credit; signing enabled but not required | Bảng 3.3 (Mục 3.3.3) | `MOVE` | Tổng hợp đặc tính phương ngữ; giữ đầy đủ giá trị capabilities. |
| 24 | `SRC-TBL-24` | Bảng 3.4, L148 | **NSE-SMB-01** | Quét TCP SYN cổng 139/445: trạng thái `open syn-ack ttl 128` | Bảng 3.4 (Mục 3.4.1) | `MOVE` | Xác nhận điều kiện tiên quyết về tính khả dụng của cổng. |
| 25 | `SRC-TBL-25` | Bảng 3.4, L149 | **NSE-SMB-02** | Khảo sát dialect qua `smb-protocols`: 5 dialect NT LM 0.12..3.0.2 | Bảng 3.4 (Mục 3.4.1) | `MOVE` | Xác nhận dịch vụ đang hỗ trợ phương ngữ cũ SMBv1. |
| 26 | `SRC-TBL-26` | Bảng 3.4, L150 | **NSE-SMB-03** | Khảo sát signing qua `smb2-security-mode`: `enabled but not required` trên 3.0.2 | Bảng 3.4 (Mục 3.4.1) | `MOVE` | Chính sách ký số quan sát từ xa cho phép kết nối không ký. |
| 27 | `SRC-TBL-27` | Bảng 3.4, L151 | **NSE-SMB-04** | Kiểm tra MS17-010 qua `smb-vuln-ms17-010`: cổng 445 open, không có script result | Bảng 3.4 (Mục 3.4.1) | `MOVE` | Phân loại `UNKNOWN / NO USABLE SCRIPT RESULT`. Tiên đề: `UNKNOWN != SAFE`. |
| 28 | `SRC-TBL-28` | Bảng 3.5, L196 | **Cấu hình máy chủ SMBv1**<br>(`EnableSMB1Protocol`) | Before: `True` $\\to$ After: `False` | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Vô hiệu hóa thành công cấu hình SMBv1 nội bộ. |
| 29 | `SRC-TBL-29` | Bảng 3.5, L197 | **Cấu hình máy chủ SMB2/3**<br>(`EnableSMB2Protocol`) | Before: `True` $\\to$ After: `True` | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Giữ nguyên cấu hình kích hoạt các phương ngữ mới. |
| 30 | `SRC-TBL-30` | Bảng 3.5, L198 | **Tính năng hệ điều hành**<br>(`FS-SMB1`) | Before: `Installed` $\\to$ After: `Installed` | Bảng 3.5 (Mục 3.5.3) | `MOVE` | `SMBv1 disabled != FS-SMB1 uninstalled`. |
| 31 | `SRC-TBL-31` | Bảng 3.5, L199 | **Dịch vụ chia sẻ tệp**<br>(`LanmanServer`) | Before: `Running` $\\to$ After: `Running` (point-in-time) | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Dịch vụ tiếp tục hoạt động tại thời điểm kiểm tra. |
| 32 | `SRC-TBL-32` | Bảng 3.5, L200 | **Trạng thái cổng dịch vụ từ xa**<br>(Cổng TCP 445 từ trạm Kali) | Before: `OPEN (syn-ack)` $\\to$ After: `OPEN` (không có cờ `--reason`) | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Cổng 445 tiếp tục mở; ghi chú rõ TCP 139 NOT REMEASURED. |
| 33 | `SRC-TBL-33` | Bảng 3.5, L201 | **Phương ngữ SMB ghi nhận từ xa**<br>(Kịch bản `smb-protocols`) | Before: 5 dialect $\\to$ After: 4 dialect (`NT LM 0.12` vắng mặt) | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Hiệu lực loại bỏ phương ngữ cũ trên bề mặt đàm phán mạng. |
| 34 | `SRC-TBL-34` | Bảng 3.5, L202 | **Phán quyết kiểm tra MS17-010**<br>(Kịch bản `smb-vuln-ms17-010`) | Before: `UNKNOWN` $\\to$ After: `UNKNOWN` (không đổi) | Bảng 3.5 (Mục 3.5.3) | `MOVE` | Tắt SMBv1 không làm Nmap đưa ra phán quyết SAFE. |
| 35 | `SRC-TBL-35` | Bảng 3.5, L203 | **Trạng thái bản vá hệ thống**<br>(Mã nhị phân driver `srv.sys`) | Before: `UNPATCHED` $\\to$ After: `UNPATCHED` (kế thừa mốc xuất phát) | Bảng 3.5 (Mục 3.5.3) | `MOVE` | `SMBv1 disabled != PATCHED`. Không thay đổi mã driver. |
| 36 | `SRC-TBL-36` | Bảng 3.6, L247 | **Vị trí kiểm soát mạng / kiến trúc đường truyền** | Before: Host-Only $\\to$ After: pfSense Transparent Bridge `bridge0` | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Cầu nối Layer 2 không thay đổi cấu trúc IP subnet. |
| 37 | `SRC-TBL-37` | Bảng 3.6, L248 | **Chính sách lọc pfSense** | Before: Chưa áp dụng $\\to$ After: Block IPv4 TCP 139/445 từ Kali tới Windows, có log | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Chính sách chặn lưu lượng SMB nhắm vào máy chủ. |
| 38 | `SRC-TBL-38` | Bảng 3.6, L249 | **Thứ tự quy tắc trên giao diện kiểm thử** | Before: Không áp dụng $\\to$ After: Block SMB_Ports (Dòng 1) xếp trên Pass baseline (Dòng 2) | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Thứ tự ưu tiên ruleset trên giao diện `CASE_C_KALI`. |
| 39 | `SRC-TBL-39` | Bảng 3.6, L250 | **Trạng thái cổng TCP 139 từ xa**<br>(Từ trạm Kali Linux) | Before: `OPEN (syn-ack)` $\\to$ After: `FILTERED (no-response)` | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Góc nhìn từ trạm Kali: cổng bị lọc trên đường truyền. |
| 40 | `SRC-TBL-40` | Bảng 3.6, L251 | **Trạng thái cổng TCP 445 từ xa**<br>(Từ trạm Kali Linux) | Before: `OPEN (syn-ack)` $\\to$ After: `FILTERED (no-response)` | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Cổng bị lọc từ xa. Tiên đề: `FILTERED != PATCHED`. |
| 41 | `SRC-TBL-41` | Bảng 3.6, L252 | **Nhật ký tường lửa pfSense**<br>(Giao diện `CASE_C_KALI`) | Before: Không có log $\\to$ After: Ghi nhận 4 sự kiện Block TCP SYN tới 139/445 | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Bằng chứng chặn thực tế; bảo lưu xung đột danh pháp CF-11. |
| 42 | `SRC-TBL-42` | Bảng 3.6, L253 | **Phán quyết kiểm tra MS17-010 từ xa**<br>(Kịch bản `smb-vuln-ms17-010`) | Before: `UNKNOWN` $\\to$ After: `UNKNOWN` (không có script result) | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Không có kết quả script trên cổng bị filtered; UNKNOWN != SAFE. |
| 43 | `SRC-TBL-43` | Bảng 3.6, L254 | **Cấu hình giao thức SMBv1 cục bộ**<br>(`EnableSMB1Protocol`) | Before: `True` $\\to$ After: `True` (tiếp tục duy trì kích hoạt) | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Máy chủ phía sau giữ nguyên SMBv1=True (Section 21). |
| 44 | `SRC-TBL-44` | Bảng 3.6, L255 | **Dịch vụ chia sẻ tệp và listener cục bộ** | Before: LanmanServer Running, 139/445 Listen $\\to$ After: Running, listener hiện diện | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Listener trỏ Section 21; LanmanServer Running là truth lock ETM-C-02 kế thừa. |
| 45 | `SRC-TBL-45` | Bảng 3.6, L256 | **Trạng thái bản vá hệ thống cục bộ**<br>(Mã nhị phân driver `srv.sys`) | Before: `UNPATCHED` $\\to$ After: `UNPATCHED` (không có thao tác cài bản vá) | Bảng 3.6 (Mục 3.6.3) | `MOVE` | Máy chủ phía sau tiếp tục UNPATCHED (Section 21). |
| 46 | `SRC-TBL-46` | Bảng 3.7, L294 | **Lớp can thiệp** | Baseline: Không can thiệp $\\mid$ Case B: Cấu hình máy chủ $\\mid$ Case C: pfSense Bridge | Bảng 3.7 (Mục 3.7.1) | `MOVE` | Tiêu chí phân định vị trí can thiệp trong ma trận 3 trạng thái. |
| 47 | `SRC-TBL-47` | Bảng 3.7, L295 | **Trạng thái cổng TCP 139 từ xa**<br>(Từ trạm Kali Linux) | Baseline: `OPEN (syn-ack)` $\\mid$ Case B: `NOT REMEASURED` $\\mid$ Case C: `FILTERED (no-response)` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | So sánh trạng thái cổng 139 qua 3 giai đoạn. |
| 48 | `SRC-TBL-48` | Bảng 3.7, L296 | **Trạng thái cổng TCP 445 từ xa**<br>(Từ trạm Kali Linux) | Baseline: `OPEN (syn-ack)` $\\mid$ Case B: `OPEN` $\\mid$ Case C: `FILTERED (no-response)` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | So sánh trạng thái cổng 445 qua 3 giai đoạn. |
| 49 | `SRC-TBL-49` | Bảng 3.7, L297 | **Phương ngữ SMB quan sát được**<br>(Từ trạm Kali Linux) | Baseline: 5 dialect $\\mid$ Case B: 4 dialect $\\mid$ Case C: `KHÔNG CÓ PHÉP ĐO TƯƠNG ỨNG` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | Case C ghi nhận rõ ràng NOT MEASURED, không suy diễn từ filtered. |
| 50 | `SRC-TBL-50` | Bảng 3.7, L298 | **Cấu hình giao thức SMBv1 cục bộ**<br>(`EnableSMB1Protocol`) | Baseline: `True` $\\mid$ Case B: `False` $\\mid$ Case C: `True` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | So sánh cấu hình SMBv1 nội bộ giữa 3 trạng thái. |
| 51 | `SRC-TBL-51` | Bảng 3.7, L299 | **LanmanServer cục bộ**<br>(Trên Windows Server 2012 R2) | Baseline: `Running` $\\mid$ Case B: `Running (point-in-time)` $\\mid$ Case C: `Running (ETM-C-02)` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | Dịch vụ chia sẻ tệp duy trì trạng thái hoạt động. |
| 52 | `SRC-TBL-52` | Bảng 3.7, L300 | **Trạng thái bản vá hệ thống cục bộ**<br>(Mã nhị phân driver `srv.sys`) | Baseline: `UNPATCHED` $\\mid$ Case B: `UNPATCHED` $\\mid$ Case C: `UNPATCHED` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | Cả 3 trạng thái đều giữ nguyên bản vá UNPATCHED. |
| 53 | `SRC-TBL-53` | Bảng 3.7, L301 | **Phán quyết kiểm tra MS17-010 từ xa**<br>(Kịch bản `smb-vuln-ms17-010`) | Cả 3 trạng thái: `UNKNOWN / NO USABLE SCRIPT RESULT` | Bảng 3.7 (Mục 3.7.1) | `MOVE` | Cả 3 trạng thái đều không đưa ra phán quyết SAFE. |

---

### 3.2. Kiểm kê 26 khối dữ kiện văn bản có nghĩa (Meaningful Narrative Fact Blocks Inventory)

| STT | Source Key | Đề mục cũ & Dòng gốc | Khối dữ kiện kỹ thuật nguồn (Narrative Fact Block) | Đích đề mục mới | Hành động (Action) | Ranh giới / Căn cứ chuyển dịch |
|---|---|---|---|---|---|---|
| 1 | `SRC-NAR-01` | Mục 3.1, L004–015 | Dẫn nhập kiến trúc Host-Only, dải mạng 192.168.56.0/24 và mục tiêu kiểm toán mốc xuất phát ban đầu | Mục 3.1.1, 3.2.1 | `REWRITE & MOVE` | Chuyển thành mạch mở đầu khoa học; gắn với Claim-01, 02, 03. |
| 2 | `SRC-NAR-02` | Mục 3.1.1, L032–045 | Phân tích chi tiết LanmanServer, FS-SMB1, cấu hình SMB1/SMB2, cờ ký số nội bộ và cơ chế Windows Firewall | Mục 3.2.1 | `REUSE & MOVE` | Giải thích ý nghĩa socket cục bộ; gắn với Claim-04, 05, 06. |
| 3 | `SRC-NAR-03` | Mục 3.1.2, L046–059 | Phân tích cơ chế lỗ hổng MS17-010 tại driver `srv.sys`, giải thích sự khác biệt giữa chuỗi FileVersion hiển thị và số nhị phân | Mục 3.2.2 | `REUSE & MOVE` | Cơ sở kỹ thuật đối chiếu bản vá; gắn với Claim-07, 08, 09. |
| 4 | `SRC-NAR-04` | Mục 3.1.2, L072–079 | Đánh giá danh mục Get-HotFix (6 hotfix), phân loại UNPATCHED và vai trò mốc phục hồi Snapshot `BASE-CLEAN-2026-10-04` | Mục 3.2.2 | `REUSE & MOVE` | Căn cứ mốc xuất phát kiểm chứng; gắn với Claim-10, 11, 12. |
| 5 | `SRC-NAR-05` | Mục 3.2, L080–091 | Dẫn nhập Kịch bản 1, mục tiêu khảo sát diện mạo dịch vụ SMB từ xa bằng Nmap từ góc nhìn trạm Kali Linux | Mục 3.3.1 | `REWRITE & MOVE` | Chuyển sang góc nhìn người kiểm thử thăm dò mạng. |
| 6 | `SRC-NAR-06` | Mục 3.2.1, L102–107 | Phân tích bước B2 (Ping sweep `-sn`) phát hiện 4 IP trực tuyến (.1, .10, .20, .100); trạm .56.100 mang nhãn UNKNOWN identity | Mục 3.3.1 | `REUSE & MOVE` | Nhận diện phạm vi trạm mạng khả dụng; gắn với Claim-13. |
| 7 | `SRC-NAR-07` | Mục 3.2.1, L108–111 | Phân tích bước B3 (Nmap ARP đơn điểm `-sn -PR`) xác nhận trạm Windows trực tuyến qua phản hồi ARP Layer 2 | Mục 3.3.1 | `REUSE & MOVE` | Khảo sát ARP đơn điểm, không phải Ping/Layer 3; gắn với Claim-14. |
| 8 | `SRC-NAR-08` | Mục 3.2.1, L112–117 | Phân tích bước B4 (SYN scan `-sS`) xác nhận cổng 139 và 445 OPEN kèm cờ phản hồi `syn-ack ttl 128` | Mục 3.3.1 | `REUSE & MOVE` | Xác nhận tiếp cận dịch vụ qua mạng; gắn với Claim-15. Tiên đề: 445 OPEN != vulnerable. |
| 9 | `SRC-NAR-09` | Mục 3.2.2, L118–121 | Phân tích bước B5 (Service version `-sV`) nhận diện dịch vụ netbios-ssn, microsoft-ds và OS fingerprint | Mục 3.3.2 | `REUSE & MOVE` | Dải nhận diện hệ điều hành từ xa; gắn với Claim-16. |
| 10 | `SRC-NAR-10` | Mục 3.2.2, L122–127 | Phân tích bước B6 (smb-protocols, smb2-capabilities DFS/Leasing/Multi-credit, signing) và tổng kết diện mạo Kịch bản 1 | Mục 3.3.2, 3.3.3 | `REUSE & MOVE` | Giữ nguyên vẹn toàn bộ giá trị capabilities; gắn với Claim-17, 18, 19. |
| 11 | `SRC-NAR-11` | Mục 3.3, L128–143 | Dẫn nhập Kịch bản 2, mục tiêu rà quét dấu hiệu MS17-010 và chi tiết 3 phép đo tiền đề NSE01–03 | Mục 3.4.1 | `TRIM & MOVE` | Xác nhận điều kiện trước khi quét lỗ hổng; gắn với Claim-20. |
| 12 | `SRC-NAR-12` | Mục 3.3.2, L153–162 | Thực thi kịch bản `smb-vuln-ms17-010` (NSE-SMB-04), quan sát cổng 445 open và không xuất hiện khối Host script results | Mục 3.4.1 | `REUSE & MOVE` | Lệnh chuẩn xác không sudo, không unsafe=0; gắn với Claim-21. |
| 13 | `SRC-NAR-13` | Mục 3.3.2, L163–166 | Phân loại phương pháp luận kết quả rà quét NSE04 thành UNKNOWN / NO USABLE SCRIPT RESULT và tiên đề UNKNOWN != SAFE | Mục 3.4.1 | `REUSE & MOVE` | Phân loại chuẩn hóa dự án; gắn với Claim-22. |
| 14 | `SRC-NAR-14` | Mục 3.3.2, L167–172 | Phân tích đối chiếu giữa remote UNKNOWN và local UNPATCHED, xác lập ranh giới an toàn không exploit | Mục 3.4.2 | `REWRITE & EXPAND` | Trọng tâm học thuật đối chiếu đa tầng; gắn với Claim-23, 24. |
| 15 | `SRC-NAR-15` | Mục 3.4, L173–182 | Dẫn nhập Case B, thao tác vô hiệu hóa SMBv1 qua lệnh PowerShell và kiểm tra cấu hình cục bộ | Mục 3.5.1 | `REUSE & MOVE` | Can thiệp cấu hình runtime nội bộ; gắn với Claim-25, 26. |
| 16 | `SRC-NAR-16` | Mục 3.4.1, L186–191 | Phân tích kết quả kiểm tra cục bộ sau can thiệp: EnableSMB1Protocol=False, FS-SMB1=Installed, LanmanServer=Running point-in-time | Mục 3.5.1 | `REUSE & MOVE` | Phân định SMBv1 disabled != FS-SMB1 uninstalled; gắn với Claim-26. |
| 17 | `SRC-NAR-17` | Mục 3.4.2, L205–215 | Đo đạc lại từ xa trong Case B bằng `smb-protocols`: loại bỏ phương ngữ NT LM 0.12, duy trì 4 dialect SMB2/3 | Mục 3.5.2 | `REUSE & MOVE` | Hiệu lực kỹ thuật của Case B trên mạng; gắn với Claim-27. |
| 18 | `SRC-NAR-18` | Mục 3.4.2, L216–223 | Đo đạc lại `smb-vuln-ms17-010`, ghi nhận TCP 139 not remeasured, TCP 445 open không cờ `--reason`, 4 tầng phân định của Case B | Mục 3.5.2, 3.5.3 | `REUSE & MOVE` | Ranh giới đo đạc thực nghiệm bắt buộc; gắn với Claim-28, 29, 30. |
| 19 | `SRC-NAR-19` | Mục 3.5, L224–233 | Dẫn nhập Case C, kiến trúc cầu nối pfSense Transparent Bridge `bridge0` và cấu hình tunables pfil_member=1, pfil_bridge=0 | Mục 3.6.1 | `REUSE & EXPAND` | Can thiệp trên đường truyền mạng Layer 2; gắn với Claim-31. |
| 20 | `SRC-NAR-20` | Mục 3.5.1, L234–242 | Thiết lập chính sách lọc Block TCP 139/445 và thứ tự quy tắc ưu tiên trên giao diện `CASE_C_KALI` | Mục 3.6.1 | `REUSE & MOVE` | Chính sách tường lửa có bật logging; gắn với Claim-32. |
| 21 | `SRC-NAR-21` | Mục 3.5.2, L258–268 | Đo đạc lại từ xa qua pfSense: cổng 139 và 445 chuyển sang filtered (lý do no-response), ghi nhận gói arp-response | Mục 3.6.2 | `REUSE & MOVE` | Thay đổi góc nhìn tiếp cận từ Kali; gắn với Claim-33. Tiên đề: FILTERED != PATCHED. |
| 22 | `SRC-NAR-22` | Mục 3.5.2, L269–277 | Phân tích nhật ký pfSense Block Log, bảo lưu xung đột quy tắc CF-11, đối chiếu 4-tuple và thời gian lượt chạy | Mục 3.6.3 | `REUSE & MOVE` | Bảo tồn nguyên vẹn xung đột danh pháp; gắn với Claim-34, 35. |
| 23 | `SRC-NAR-23` | Mục 3.5.2, L278–283 | Đo đạc lại MS17-010 tiếp tục UNKNOWN; kiểm tra trạng thái máy chủ Windows qua Section 21 của `RUN4_PAUSE_STATE_REPORT.txt` | Mục 3.6.2, 3.6.3 | `REUSE & MOVE` | Nêu rõ Section 21 thiếu direct final service measurement; LanmanServer Running là truth lock ETM-C-02 kế thừa; gắn với Claim-36, 37. *(Thời lượng 0.51s tại dòng 278 RETIRE CÓ LÝ DO)*. |
| 24 | `SRC-NAR-24` | Mục 3.6, L284–289, 303–306 | Tổng quan so sánh thực nghiệm, đối chiếu giữa đường cơ sở và Case B (can thiệp tầng giao thức) | Mục 3.7.1, 3.7.2 | `REWRITE & MOVE` | Phân tích đối chiếu tác động cấu hình máy chủ; gắn với Claim-38, 39. |
| 25 | `SRC-NAR-25` | Mục 3.6, L307–310 | Đối chiếu giữa Case B và Case C (can thiệp tầng mạng), phân định hai vị trí phòng thủ độc lập, 5 tiên đề chân lý | Mục 3.7.2 | `REWRITE & MOVE` | Đúc kết chiều sâu an ninh thực nghiệm; gắn với Claim-40. |
| 26 | `SRC-NAR-26` | Mục 3.7, L311–318 | Tổng kết toàn bộ chương, đối chiếu RQ3/RQ4 và xác lập ranh giới an ninh thực nghiệm bàn giao sang Chương 4 | Mục 3.8 | `REWRITE & MOVE` | Bàn giao dữ kiện kỹ thuật sạch, không lấn sân Chương 4; gắn với Claim-41. |

---

### 3.3. Tổng kết Mẫu số định lượng (Explicit Denominator Summary)

- **Tổng số đơn vị dữ kiện nguồn được kiểm kê:** **79 mục** (53 hàng dữ liệu của 7 bảng cũ + 26 khối fact văn bản có nghĩa).
- **Phân loại hành động đối với 79 mục:**
  - `REUSE / MOVE / EXPAND / SYNTHESIZE`: **78 mục** được bảo toàn và chuyển dịch nguyên vẹn vào cấu trúc mới.
  - `RETIRE CÓ LÝ DO`: **1 mục** duy nhất (Thời lượng quét 0.51 giây tại dòng 278 của `CHAPTER_3_DRAFT_R2.md`, do là số đo thời gian chạy đơn lẻ của Nmap, không có đồng hồ đối chứng độc lập và không mang giá trị chân lý an ninh).
- **Mức độ bao phủ:** Toàn bộ 78 mục chuyển dịch được bao trọn hoàn toàn bởi **41 luận điểm kỹ thuật chuẩn hóa** (`Claim-01` đến `Claim-41`) trong Ma trận truy vết chi tiết tại Mục 4 dưới đây.

---

## 4. MA TRẬN TRUY VẾT CHI TIẾT TỪNG LUẬN ĐIỂM (GRANULAR CLAIM TRACEABILITY MATRIX)

Ma trận này quản lý toàn diện 41 luận điểm kỹ thuật bao trùm toàn bộ mẫu số nguồn, đối soát trực tiếp tới Stable Evidence IDs đã đăng ký trong `work/do-an/EVIDENCE_REGISTER.md` và các tệp chứng cứ canonical:

| Claim ID | Vị trí nguồn trong Draft R2 | Stable Evidence ID & Tệp nguồn canonical | Cấp độ bằng chứng | Dữ kiện kỹ thuật bảo toàn | Đích đề mục mới | Hành động | Ranh giới kỹ thuật bắt buộc |
|---|---|---|---|---|---|---|---|
| **Claim-01** | Dòng 10–11, 20–22 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-01`, `ENV-CORE-05`<br>`chapter3/evidence/baseline/Final_PreDemo_Audit.txt`, `Windows_PreDemo_01_Network_SMB.png`, `VirtualBox_HostOnly_Config.txt` | `PRIMARY_LOCAL_STATE`, `PRIMARY_VISUAL` | Topology Host-Only; Kali IP `192.168.56.10/24` (eth0); Windows IP `192.168.56.20/24` (Ethernet); không default route, không card NAT/Bridged. | 3.2.1 | `REUSE & MOVE` | Mạng lab cô lập; không chứng minh kết nối ngoài Internet. |
| **Claim-02** | Dòng 12, 23–24 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-01`, `ENV-CORE-05`<br>`chapter3/evidence/baseline/Windows_PreDemo_01_Network_SMB.png`, `Final_PreDemo_Audit.txt` | `PRIMARY_VISUAL`, `PRIMARY_LOCAL_STATE` | LanmanServer đang chạy (`Running`, Automatic); tính năng `FS-SMB1` hiển thị trạng thái `Installed`. | 3.2.1 | `REUSE & MOVE` | Trạng thái dịch vụ cục bộ mốc ban đầu; chưa phản ánh góc nhìn mạng từ xa. |
| **Claim-03** | Dòng 12, 25 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-01`, `ENV-CORE-05`<br>`chapter3/evidence/baseline/Final_PreDemo_Audit.txt`, `Windows_PreDemo_01_Network_SMB.png` | `PRIMARY_LOCAL_STATE`, `PRIMARY_VISUAL` | Cấu hình máy chủ SMB: `EnableSMB1Protocol : True`, `EnableSMB2Protocol : True`. | 3.2.1 | `REUSE & MOVE` | Thuộc tính cấu hình nội bộ; phương ngữ thực tế đàm phán phải đo từ xa qua mạng. |
| **Claim-04** | Dòng 12, 26 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-01`<br>`chapter3/evidence/baseline/Final_PreDemo_Audit.txt` | `PRIMARY_LOCAL_STATE` | Thuộc tính ký số nội bộ: `EnableSecuritySignature : False`, `RequireSecuritySignature : False`. | 3.2.1 | `REUSE & MOVE` | Phân biệt rõ thiết lập cờ cục bộ với chính sách signing quan sát từ xa ở Kịch bản 1. |
| **Claim-05** | Dòng 12, 27, 34, 36 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-01`, `ENV-CORE-05`<br>`chapter3/evidence/baseline/Windows_PreDemo_01_Network_SMB.png`, `Final_PreDemo_Audit.txt` | `PRIMARY_VISUAL`, `PRIMARY_LOCAL_STATE` | Socket lắng nghe cục bộ: PID 4 lắng nghe TCP 445 (`::`) và TCP 139 (`192.168.56.20`) qua lệnh PowerShell `Get-NetTCPConnection` (không phải netstat). | 3.2.1 | `REUSE & MOVE` (Hình 3.2) | Socket lắng nghe cục bộ != cổng mở trên mạng ngoài. Mô tả chính xác lệnh PowerShell `Get-NetTCPConnection -State Listen \| Where-Object { $_.LocalPort -in 139,445 }`. |
| **Claim-06** | Dòng 28–30, 38–44 (Mục 3.1.1 & Bảng 3.1) | `ENV-CORE-04`<br>`chapter3/evidence/baseline/Windows_PreDemo_02_Firewall.png`, `Windows_FirewallPrep_Final.txt` | `PRIMARY_VISUAL`, `PRIMARY_LOCAL_STATE` | 3 profile Windows Firewall Enabled=True; 16 rule chia sẻ tệp mặc định False; rule tùy biến `ATTT Lab SMB 139-445` Inbound Allow TCP 139,445 chỉ cho phép nguồn `192.168.56.10`. | 3.2.1 | `REUSE & MOVE` (Bảng 3.1) | Quy tắc tường lửa nội bộ chỉ là điều kiện cần; khả năng tiếp cận thực tế phải đo từ Kali. |
| **Claim-07** | Dòng 48, 64 (Mục 3.1.2 & Bảng 3.2) | `ENV-CORE-03`<br>`chapter3/evidence/baseline/Windows_MS17010_01_SrvSysVersion.png` | `PRIMARY_VISUAL` | Chuỗi FileVersion hiển thị của driver `srv.sys` tại `System32\drivers\srv.sys` là `6.3.9600.16384` (`winblue_rtm.130821-1623`). | 3.2.2 | `REUSE & MOVE` (Hình 3.3 Panel A) | Chuỗi hiển thị trong PowerShell không phải giá trị phiên bản số nhị phân dùng để so sánh. |
| **Claim-08** | Dòng 50, 65 (Mục 3.1.2 & Bảng 3.2) | `ENV-CORE-03`<br>`chapter3/evidence/baseline/Windows_MS17010_01_SrvSysVersion.png` | `PRIMARY_VISUAL` | Ghép 4 trường số FileMajor/Minor/Build/PrivatePart cho giá trị phiên bản số nhị phân thực tế là `6.3.9600.16421`. | 3.2.2 | `REUSE & MOVE` (Hình 3.3 Panel A) | Phiên bản số nhị phân là căn cứ kỹ thuật chuẩn xác duy nhất để so sánh với ngưỡng bản vá. |
| **Claim-09** | Dòng 50, 66–67 (Mục 3.1.2 & Bảng 3.2) | `SOURCE_AUTHORITY`<br>Microsoft Security Bulletin MS17-010, KB4012213/KB4012216 (tài liệu Microsoft S032 / S005) | `EXTERNAL_AUTHORITY` | Ngưỡng bản vá tối thiểu của Windows Server 2012 R2 là `6.3.9600.18604`; so sánh số học: $6.3.9600.16421 < 6.3.9600.18604$. | 3.2.2 | `REUSE & MOVE` (Bảng 3.2) | Căn cứ ngưỡng phải dẫn nguồn chính thức Microsoft (S032), tệp mapping nội bộ không phải external authority. |
| **Claim-10** | Dòng 52, 68 (Mục 3.1.2 & Bảng 3.2) | `ENV-CORE-03`<br>`chapter3/evidence/baseline/Windows_MS17010_02_Hotfix.png`, `Final_PreDemo_Audit.txt` Section 3 | `PRIMARY_VISUAL`, `PRIMARY_LOCAL_STATE` | Danh mục local `Get-HotFix` inventory ghi nhận 6 bản cập nhật năm 2014 (KB2919355..KB2949621); hoàn toàn thiếu vắng KB4012213 hoặc KB4012216. | 3.2.2 | `REUSE & MOVE` (Hình 3.3 Panel B) | Local Get-HotFix inventory là bằng chứng bổ trợ chứng minh thiếu bản vá đã biết, không đại diện cho toàn bộ lịch sử cập nhật hệ điều hành. Nguồn: `Final_PreDemo_Audit.txt` Section 3; loại bỏ snapshot khỏi nguồn hotfix. |
| **Claim-11** | Dòng 54, 69 (Mục 3.1.2 & Bảng 3.2) | `ENV-CORE-03` + Microsoft S032 Authority<br>`chapter3/evidence/baseline/Windows_MS17010_01_SrvSysVersion.png`, `Final_PreDemo_Audit.txt` Section 4 | `PRIMARY_LOCAL_STATE` (Derived Interpretation) | Phân loại trạng thái bản vá hệ thống nội bộ: **UNPATCHED** đối với lỗ hổng MS17-010. | 3.2.2 | `REUSE & MOVE` (Bảng 3.2) | Phân loại UNPATCHED là diễn giải suy luận (derived interpretation) dựa trên đối chiếu phiên bản nhị phân thực tế với ngưỡng Microsoft S032; dữ kiện primary là phiên bản driver `srv.sys` và hotfix, authority là Microsoft S032; không tự coi tổng hợp là primary observation. |
| **Claim-12** | Dòng 56, 70 (Mục 3.1.2 & Bảng 3.2) | `ENV-CORE-02`<br>`chapter3/evidence/baseline/Before_Demo_Snapshots.txt` | `PRIMARY_LOCAL_STATE` | Snapshot `BASE-CLEAN-2026-10-04` (Before Demo) ghi nhận trên cả hai máy ảo ở trạng thái poweroff, làm mốc phục hồi chuẩn cho các kịch bản. | 3.2.2 | `REUSE & MOVE` | Mốc phục hồi kiểm chứng; không tự bịa đặt mốc thời gian rollback cụ thể ngoài dữ kiện đã xác minh. |
| **Claim-13** | Dòng 86–87, 96, 102–107 (Mục 3.2.1 & Bảng 3.3 bước B2) | `S1-RAW-01`<br>`chapter3/evidence/scenario1/b2_host_discovery.nmap` | `PRIMARY_RAW` | Quét Ping sweep (`-sn`) dải mạng phát hiện 4 IP trực tuyến (.1, .10, .20, .100); `.56.100` mang nhãn bắt buộc `UNKNOWN identity`. | 3.3.1 | `REUSE & MOVE` | Không tự gán danh tính cho trạm .56.100 khi không có căn cứ. |
| **Claim-14** | Dòng 88–89, 97, 108–111 (Mục 3.2.1 & Bảng 3.3 bước B3) | `S1-RAW-02`<br>`chapter3/evidence/scenario1/b3_target_alive.nmap` | `PRIMARY_RAW` | Quét ARP đơn điểm (`-sn -PR`): trạm `.56.20` phản hồi trực tuyến `Host is up (0.00037s latency)`, MAC `08:00:27:0B:DA:B7`. | 3.3.1 | `REUSE & MOVE` | Khảo sát kiểm tra trực tuyến bằng ARP đơn điểm (Layer 2) theo dòng 1 raw file `-sn -PR`, không phải Ping/Layer 3. |
| **Claim-15** | Dòng 98, 112–117 (Mục 3.2.1 & Bảng 3.3 bước B4) | `S1-RAW-03`<br>`chapter3/evidence/scenario1/b4_smb_ports.nmap`, `chapter3/evidence/scenario1/Scenario1_B4_SMB_Ports.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Quét TCP SYN: cổng 139 và 445 `OPEN`, cờ phản hồi `syn-ack`, TTL 128. Tiên đề: `445 OPEN != vulnerable`. | 3.3.1 | `REUSE & MOVE` (Hình 3.4) | Cổng mở chỉ chứng minh khả năng tiếp cận giao vận, không chứng minh tồn tại lỗ hổng hay phiên SMB thành công. |
| **Claim-16** | Dòng 99, 118–121 (Mục 3.2.2 & Bảng 3.3 bước B5) | `S1-RAW-04`<br>`chapter3/evidence/scenario1/b5_smb_version.nmap`, `chapter3/evidence/scenario1/Scenario1_B5_SMB_Version.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Nmap -sV thăm dò: 139 netbios-ssn, 445 microsoft-ds; dải fingerprint hệ điều hành `Windows Server 2008 R2 - 2012`. | 3.3.2 | `REUSE & MOVE` (Hình 3.5 Panel A) | Dải fingerprint không định danh tuyệt đối bản Windows Server 2012 R2. |
| **Claim-17** | Dòng 100, 118–122 (Mục 3.2.2 & Bảng 3.3 bước B6) | `S1-RAW-05`<br>`chapter3/evidence/scenario1/b6_smb_nse.nmap`, `chapter3/evidence/scenario1/Scenario1_B6_SMB_NSE_A.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Kịch bản `smb-protocols` phát hiện 5 phương ngữ: `NT LM 0.12 (SMBv1)`, `2.0.2`, `2.1`, `3.0`, `3.0.2`. Kịch bản `smb2-capabilities` ghi nhận: DFS trên 2.0.2..3.0.2; Leasing và Multi-credit trên 2.1..3.0.2. Tiên đề: `SMBv1 enabled != MS17-010 confirmed`. | 3.3.2 | `REUSE & MOVE` (Hình 3.5 Panel B, Bảng 3.3) | Hỗ trợ phương ngữ SMBv1 chỉ là điều kiện cần; bảo toàn đầy đủ các thuộc tính capabilities của SMB2/3. |
| **Claim-18** | Dòng 100, 122–124 (Mục 3.2.2 & Bảng 3.3 bước B6) | `S1-RAW-05`<br>`chapter3/evidence/scenario1/b6_smb_nse.nmap`, `chapter3/evidence/scenario1/Scenario1_B6_SMB_NSE_A.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Kịch bản `smb2-security-mode` ghi nhận chính sách ký số: `message_signing: enabled but not required` trên dialect 3.0.2. | 3.3.2 | `REUSE & MOVE` (Hình 3.5 Panel B) | Chính sách ký số quan sát từ xa độc lập với cờ cấu hình nội bộ `EnableSecuritySignature : False`. |
| **Claim-19** | Dòng 100, 125 (Mục 3.2.2 & Bảng 3.3 bước B6) | `S1-RAW-05`<br>`chapter3/evidence/scenario1/b6_smb_nse.nmap`, `chapter3/evidence/scenario1/Scenario1_B6_SMB_NSE_A.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Kịch bản `smb-os-discovery` không có đầu ra khả dụng (không in ra thông tin định danh hệ điều hành). | 3.3.2 | `REUSE & MOVE` | Không suy đoán nguyên nhân lỗi khi Nmap không xuất chuỗi giải thích. |
| **Claim-20** | Dòng 134–143, 148–150 (Mục 3.3.1 & Bảng 3.4) | `S2-RAW-01`, `S2-RAW-02`, `S2-RAW-03`<br>`chapter3/evidence/scenario2/NSE-SMB-01_ports.nmap`, `chapter3/evidence/scenario2/NSE-SMB-02_protocols.nmap`, `chapter3/evidence/scenario2/NSE-SMB-03_signing.nmap` | `PRIMARY_RAW` | Chuỗi đo đạc NSE01–03 tái xác nhận: cổng 139/445 mở syn-ack, 5 dialect hiện diện, signing enabled but not required. | 3.4.1 | `TRIM & MOVE` (Bảng 3.4) | Đóng vai trò kiểm tra điều kiện tiên quyết trước khi chạy kịch bản MS17-010. |
| **Claim-21** | Dòng 151, 153–161 (Mục 3.3.2 & Bảng 3.4) | `S2-RAW-04`, `S2-META-01`<br>`chapter3/evidence/scenario2/NSE-SMB-04_ms17010.nmap`, `chapter3/evidence/scenario2/Scenario2_NSE04_MS17010.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Lệnh operator ghi nhận từ ảnh và manifest: `nmap -p 445 -n -T3 --max-retries 2 --script smb-vuln-ms17-010 -oA evidence/nse-smb/NSE-SMB-04_ms17010 192.168.56.20` (không có `sudo`, không có `unsafe=0`). Argv dòng 1 raw file: `/usr/lib/nmap/nmap --privileged ...`. Cổng 445 OPEN; `Nmap done` hoàn tất; không xuất hiện khối `Host script results:`. | 3.4.1 | `REUSE & MOVE` (Hình 3.6) | Chép chính xác operator command không sudo, không unsafe=0; ghi nhận recorded argv; bản rút gọn trong văn bản phải được đánh dấu. |
| **Claim-22** | Dòng 151, 162–166 (Mục 3.3.2 & Bảng 3.4) | `S2-RAW-04` + Methodological Rule<br>`chapter3/evidence/scenario2/NSE-SMB-04_ms17010.nmap`, phân loại phương pháp luận | `PRIMARY_RAW` + Methodological Rule | Phân loại dự án: **`UNKNOWN / NO USABLE SCRIPT RESULT`**. Nguyên nhân nội bộ chưa xác lập. Tiên đề: **`UNKNOWN != SAFE`**. | 3.4.1 | `REUSE & MOVE` | UNKNOWN là nhãn phân loại dự án, không phải chuỗi Nmap in ra; không suy diễn thành VULNERABLE hay SAFE. |
| **Claim-23** | Dòng 167–168 (Mục 3.3.2) | Cross-layer synthesis<br>Đối chứng chéo `chapter3/evidence/scenario2/NSE-SMB-04_ms17010.nmap` và `chapter3/evidence/baseline/Windows_MS17010_01_SrvSysVersion.png` kèm tài liệu Microsoft S032 | Tổng hợp đối chứng đa tầng | Hai trục dữ kiện độc lập hoàn toàn: Trục từ xa (UNKNOWN) vs Trục nội bộ (UNPATCHED). | 3.4.2 | `REWRITE & EXPAND` (Hình 3.7 mới) | Local UNPATCHED không biến remote thành VULNERABLE; remote UNKNOWN không biến máy thành SAFE. Dẫn nguồn Microsoft S032. |
| **Claim-24** | Dòng 169–172 (Mục 3.3.2) | Scope lock dự án đã phê duyệt | Institutional / Methodological Constraint | Hoàn toàn không có hành vi exploit, RCE hay Meterpreter trong phạm vi thực nghiệm đã phê duyệt. | 3.4.2 | `REUSE & MOVE` | Ranh giới thực nghiệm kiểm thử an toàn có kiểm soát, không phá hoại. |
| **Claim-25** | Dòng 177–180 (Mục 3.4.1) | `B-ACTION-01`, `B-META-01`<br>`chapter3/evidence/case_b/SMBv1_Remediation_02_Action.png`, `chapter3/evidence/case_b/SMBv1_Remediation_Run_Manifest.txt` | `PRIMARY_VISUAL`, `SECONDARY_META` | Lệnh thực thi Case B: `Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force`. Can thiệp cấu hình runtime. | 3.5.1 | `REUSE & MOVE` (Hình 3.8 Panel 2) | Can thiệp cấu hình runtime; không phải thao tác cài đặt bản vá hệ thống hay gỡ bỏ tính năng. Full path chuẩn hóa. |
| **Claim-26** | Dòng 181–189, 196–199, 203 (Mục 3.4.1 & Bảng 3.5) | `B-LOCAL-02`<br>`chapter3/evidence/case_b/SMBv1_Remediation_03_After_Local.png` | `PRIMARY_VISUAL` | Xác nhận sau can thiệp: `EnableSMB1Protocol : False`, `EnableSMB2Protocol : True`, `FS-SMB1 : Installed`, `LanmanServer : Running` tại thời điểm kiểm tra (point-in-time); driver `srv.sys` giữ nguyên trạng thái UNPATCHED kế thừa. | 3.5.1 | `REUSE & MOVE` (Hình 3.8 Panel 3, Bảng 3.5) | `SMBv1 disabled != FS-SMB1 uninstalled`; `SMBv1 disabled != PATCHED`. Chưa chứng minh tính liên tục dịch vụ, đàm phán thành công hay tải thực tế. |
| **Claim-27** | Dòng 201, 207–215 (Mục 3.4.2 & Bảng 3.5) | `B-RAW-01`<br>`chapter3/evidence/case_b/NSE-SMB-02_protocols.nmap`, `chapter3/evidence/case_b/SMBv1_Remediation_04_NSE02_Protocols.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Đo lại `smb-protocols`: chỉ còn 4 dialect (`2.0.2`, `2.1`, `3.0`, `3.0.2`); `NT LM 0.12 (SMBv1)` hoàn toàn vắng mặt khỏi danh sách quan sát được. | 3.5.2 | `REUSE & MOVE` (Hình 3.9, Bảng 3.5) | Phương ngữ SMBv1 vắng mặt không đồng nghĩa máy chủ hết lỗ hổng hay cổng 445 đã đóng. |
| **Claim-28** | Dòng 196 (Bảng 3.5), 209 (Mục 3.4.2) | `B-META-01`, `B-RAW-01`<br>`chapter3/evidence/case_b/SMBv1_Remediation_Run_Manifest.txt`, phạm vi lệnh quét | `SECONDARY_META`, `PRIMARY_RAW` | Cổng TCP 139 **KHÔNG ĐƯỢC ĐO LẠI** trong Case B (`NOT REMEASURED`). | 3.5.2 | `REUSE & MOVE` (Bảng 3.5) | Tuyệt đối không suy diễn trạng thái cổng 139 khi không có phép đo lại tương ứng. Ghi rõ tại ghi chú Bảng 3.5. |
| **Claim-29** | Dòng 200 (Bảng 3.5), 209 (Mục 3.4.2) | `B-RAW-02`<br>`chapter3/evidence/case_b/NSE-SMB-04_ms17010.nmap` dòng 5 | `PRIMARY_RAW` | Cổng TCP 445 ở trạng thái `OPEN` nhưng lệnh đo lại không sử dụng cờ `--reason`. | 3.5.2 | `REUSE & MOVE` (Bảng 3.5) | Không tự gán cờ `syn-ack ttl 128` cho kết quả đo lại cổng 445 khi raw không xuất dữ kiện. |
| **Claim-30** | Dòng 202 (Bảng 3.5), 216–219 (Mục 3.4.2) | `B-RAW-02`<br>`chapter3/evidence/case_b/NSE-SMB-04_ms17010.nmap` dòng 4–6, `chapter3/evidence/case_b/SMBv1_Remediation_05_NSE04_MS17010.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Đo lại kịch bản MS17-010 tiếp tục ghi nhận `UNKNOWN / NO USABLE SCRIPT RESULT`. | 3.5.2 | `REUSE & MOVE` (Bảng 3.5) | Tắt SMBv1 không làm Nmap đưa ra kết luận VULNERABLE hay SAFE; UNKNOWN != SAFE. |
| **Claim-31** | Dòng 228–233, 247 (Mục 3.5.1 & Bảng 3.6) | `C-IFACE-01`, `C-BRIDGE-01`, `C-TUNE-DIRECT-01`, `C-META-01`<br>`chapter3/evidence/case_c/pfSense_03_Interface_Assignment.png`, `pfSense_04_Bridge.png`, `pfSense_05_Bridge_Filtering.png`, `pfSense_Remediation_Run_Manifest.txt` | `PRIMARY_VISUAL`, `SECONDARY_META` | pfSense Transparent Bridge Layer 2: `bridge0` (em2 CASE_C_KALI, em3 CASE_C_WINDOWS), giữ phẳng subnet 192.168.56.0/24, không routing Layer 3, tunables `pfil_member=1`, `pfil_bridge=0`. | 3.6.1 | `REUSE & EXPAND` (Hình 3.10 mới) | CẤM dùng từ "định tuyến qua pfSense" (phải dùng "đi qua cầu nối pfSense"). Tên tệp không viết tắt. |
| **Claim-32** | Dòng 234–240, 248–249 (Mục 3.5.1 & Bảng 3.6) | `C-RULE-02`, `C-RULE-03`<br>`C-RULE-02` = `chapter3/evidence/case_c/pfSense_07_Block_Rule_Config.png`<br>`C-RULE-03` = `chapter3/evidence/case_c/pfSense_08_Rule_Order.png` | `PRIMARY_VISUAL` | Quy tắc Block TCP từ Kali (.56.10) tới Windows (.56.20) cổng 139, 445 có bật Log (`C-RULE-02` trong ảnh 07) đặt ở Dòng 1, ngay trên quy tắc Pass baseline Dòng 2 (`C-RULE-03` trong ảnh 08). | 3.6.1 | `REUSE & MOVE` (Hình 3.11, Bảng 3.6) | Ghi nhận chính xác quan hệ ID ↔ tệp theo register; hiệu lực chặn thực tế bắt buộc phải chứng minh qua đo đạc Nmap và log. |
| **Claim-33** | Dòng 250–251, 260–268 (Mục 3.5.2 & Bảng 3.6) | `C-RAW-01`, `C-VIS-01`<br>`chapter3/evidence/case_c/NSE-SMB-01_ports.nmap`, `chapter3/evidence/case_c/pfSense_CaseC_09_NSE01_Ports_CANONICAL.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Đo lại từ Kali: Cổng 139 và 445 chuyển sang trạng thái `filtered` do `no-response`. Nmap ghi nhận host up nhờ `received arp-response` (dòng 262). Tiên đề: `FILTERED != PATCHED`. | 3.6.2 | `REUSE & MOVE` (Hình 3.12, Bảng 3.6) | Filtered chỉ phản ánh góc nhìn mạng từ Kali, không đồng nghĩa máy chủ đã đóng cổng hay đã vá lỗi. Ghi rõ arp-response. |
| **Claim-34** | Dòng 252, 269–275 (Mục 3.5.2 & Bảng 3.6) | `C-LOG-01`<br>`chapter3/evidence/case_c/pfSense_10_Block_Log_CANONICAL.png` | `PRIMARY_VISUAL_WITH_BOUNDED_CONFLICT` | Nhật ký pfSense ghi nhận 4 sự kiện Block màu đỏ đối với gói tin TCP SYN từ .56.10 tới .56.20 trên cổng 139/445 trong lượt chạy canonical. | 3.6.3 | `REUSE & MOVE` (Hình 3.13, Bảng 3.6) | Đối chiếu theo run lineage và bộ 4 thông số (IP nguồn, IP đích, cổng, TCP SYN); không giả định đồng bộ đồng hồ tuyệt đối. |
| **Claim-35** | Dòng 276–277 (Mục 3.5.2) | `C-LOG-01` (CF-11 bounded conflict)<br>`chapter3/evidence/case_c/pfSense_10_Block_Log_CANONICAL.png` | `PRIMARY_VISUAL_WITH_BOUNDED_CONFLICT` | **BẢO LƯU XUNG ĐỘT DANH PHÁP (CF-11):** Ảnh hiển thị `CASE C baseline pass... (100000104)` đối chiếu với closure `Block SMB... (1000000104)`. | 3.6.3 | `REUSE & MOVE` (Hình 3.13) | BẢO TỒN NGUYÊN VẸN XUNG ĐỘT; TUYỆT ĐỐI KHÔNG CẮT CỘT RULE ĐỂ CHE GIẤU. Không quy thuộc đích danh named rule ID. |
| **Claim-36** | Dòng 253, 278 (Mục 3.5.2 & Bảng 3.6) | `C-RAW-02`, `C-VIS-02`<br>`chapter3/evidence/case_c/NSE-SMB-04_ms17010.nmap`, `chapter3/evidence/case_c/pfSense_CaseC_11_NSE04_MS17010_CANONICAL.png` | `PRIMARY_RAW`, `PRIMARY_VISUAL` | Đo lại MS17-010: cổng 445 báo filtered, không có Host script results $\\to$ `UNKNOWN / NO USABLE SCRIPT RESULT`. Thời lượng 0.51s retire có lý do. | 3.6.2, 3.6.3 | `REUSE & MOVE` (Bảng 3.6) | FILTERED là trạng thái cổng; script verdict là UNKNOWN. Bỏ suy diễn "script không gửi probe" không có căn cứ direct evidence. |
| **Claim-37** | Dòng 254–256, 280 (Mục 3.5.2 & Bảng 3.6) | `C-CLOSURE-01` (Section 21) + `ETM-C-02` truth lock<br>`chapter3/evidence/case_c/RUN4_PAUSE_STATE_REPORT.txt` (Section 21 dòng 376–384) | `SECONDARY_META_CLOSURE` + Canonical Truth Lock | Trạng thái Windows ghi nhận cuối lượt theo Section 21: SMB1=True, SMB2=True, socket Listen 139/445, driver `srv.sys` 6.3.9600.16421 UNPATCHED. Trạng thái `LanmanServer: Running` là canonical truth lock kế thừa (`ETM-C-02` từ baseline và Section 8 dòng 162). | 3.6.3 | `REUSE & MOVE` (Bảng 3.6) | Ghi nhận rõ Section 21 (dòng 376–384) không có direct service measurement cuối lượt; LanmanServer: Running là truth lock kế thừa, không dùng baseline giả làm direct local retest mới. |
| **Claim-38** | Dòng 294–301 (Mục 3.6 & Bảng 3.7) | Cross-layer synthesis<br>Tổng hợp đối chiếu chéo 83 tệp chứng cứ thực nghiệm | Ma trận so sánh đa chiều | Bảo toàn nguyên vẹn 8 hàng dữ liệu chuẩn hóa của Bảng 3.7 cũ trên schema riêng 8 tiêu chí tổng hợp; cột Case C hàng dialect ghi rõ **KHÔNG CÓ PHÉP ĐO TƯƠNG ỨNG / NOT MEASURED**. Bảng 3.5 giữ schema riêng 8 thuộc tính Case B, không ép giống nhau. | 3.7.1 | `REUSE & MOVE` (Bảng 3.7 mới) | Không suy diễn từ cổng FILTERED thành kết quả `smb-protocols`. Không xếp hạng giải pháp nào tốt hơn. Đồng bộ hai bảng giữ đúng schema đặc thù. |
| **Claim-39** | Dòng 303–308 (Mục 3.6) | Phân tích đối chiếu đa tầng | Tổng hợp phân tích khoa học | Phân định hai vị trí can thiệp độc lập: Lớp cấu hình máy chủ (Case B) vs Lớp kiểm soát đường mạng (Case C). Cả hai không thay đổi driver nhân `srv.sys`. | 3.7.2 | `REWRITE & EXPAND` (Hình 3.14 mới) | Hai biện pháp độc lập, không cấu thành một cấu hình gộp đã thử nghiệm. Cả hai không thay thế được bản vá hệ điều hành. |
| **Claim-40** | Dòng 309–310 (Mục 3.6) | Khóa tiên đề phương pháp luận | Methodological Truth Locks | 5 tiên đề chân lý: 445 OPEN != vulnerable, SMBv1 enabled != MS17-010 confirmed, SMBv1 disabled != PATCHED, FILTERED != PATCHED, UNKNOWN != SAFE. | 3.7.2 | `REUSE & MOVE` | Ranh giới tuyệt đối của Chương 3: chỉ phản ánh dữ kiện đo đạc thực tế, không khuyến nghị quản trị (dành cho Chương 4). |
| **Claim-41** | Dòng 311–318 (Mục 3.7) | Tổng kết toàn chương | Synthesis Narrative | Tóm lược 5 phát hiện cốt lõi đã chứng minh, khép lại Chương 3 và bàn giao dữ kiện kỹ thuật sạch cho Chương 4. | 3.8 | `REWRITE & MOVE` | Không lấn sân sang đánh giá rủi ro doanh nghiệp, chính sách vá lỗi hay khuyến nghị Defense-in-Depth (thuộc Chương 4). |

---

## 5. CHIẾN LƯỢC CẢI TIẾN VĂN PHONG VÀ KHẢ NĂNG TIẾP CẬN CHO ĐỘC GIẢ (NARRATIVE STRATEGY)

Để đạt mục tiêu tối thượng: *"Một người không có kiến thức chuyên sâu ATTT vẫn hiểu tác giả đang làm gì, tại sao làm và từng kết quả chứng minh điều gì"*, bản đồ chuyển dịch nội dung đề xuất 4 giải pháp cụ thể:

1. **Chuyển hóa từ "Nhật ký câu lệnh" sang "Mạch truyện khoa học":**
   - *Cách viết cũ:* "Tiếp theo thực thi lệnh nmap -p 139,445 --reason 192.168.56.20, kết quả hiển thị 139 open, 445 open..."
   - *Cách viết mới (chuẩn hóa ở R3-1):* "Để kiểm tra xem trạm kiểm thử có thể tương tác với máy chủ qua các cổng chia sẻ tệp hay không, một phép quét thăm dò được thực hiện nhắm vào hai cổng dịch vụ tiêu chuẩn là TCP 139 và 445. Kết quả ghi nhận cả hai cổng đều tiếp nhận kết nối và phản hồi gói tin SYN-ACK, xác nhận bề mặt dịch vụ SMB đã sẵn sàng trên đường truyền mạng..."
2. **Làm nổi bật các câu hỏi dẫn dắt tại đầu mỗi đề mục:**
   - Người đọc luôn được định hướng trước: *Phần này trả lời cho câu hỏi gì?* trước khi đối diện với các bảng số liệu hay ảnh terminal.
3. **Giải thích trực quan các thuật ngữ kỹ thuật cốt lõi:**
   - Giải thích ngắn gọn và dễ hiểu các khái niệm: *Cổng mở (Open) nghĩa là gì*, *Cổng bị lọc (Filtered) khác gì với Cổng đóng (Closed)*, *Phương ngữ SMB (Dialect) là gì*, *Tại sao không nhận được kết quả (UNKNOWN) không có nghĩa là an toàn (SAFE)*.
4. **Phân định rạch ròi giữa Quan sát thực tế và Ý nghĩa an ninh:**
   - Luôn tách bạch: *Công cụ nhìn thấy gì trên màn hình* và *Về mặt bảo mật, điều đó chứng minh được đến đâu*. Tuyệt đối không để người đọc ngộ nhận rằng việc thấy cổng mở hay hỗ trợ SMBv1 là đã tấn công thành công máy chủ.

---

## 6. BẢO ĐẢM TÍNH TOÀN VẸN VÀ KHÔNG THẤT THOÁT DỮ LIỆU (COVERAGE VERIFICATION)

- **Mẫu số định lượng xác lập (Explicit Denominator):** Toàn bộ **79/79 đơn vị dữ kiện nguồn** (53 hàng dữ liệu thực tế của 7 bảng cũ + 26 khối fact văn bản có nghĩa bao trọn từ dòng 1 đến 318 của `CHAPTER_3_DRAFT_R2.md`) đã được kiểm kê chi tiết tại Mục 3; trong đó 78 mục được chuyển dịch nguyên vẹn (REUSE/MOVE/EXPAND) và 1 mục duy nhất được retire có lý do minh bạch (thời lượng quét 0.51 giây tại dòng 278).
- **Mức độ bao phủ luận điểm (Claim Coverage):** Toàn bộ **41/41 luận điểm kỹ thuật** (100% bộ khung luận điểm chuẩn hóa) trong Ma trận truy vết chi tiết tại Mục 4 đã bao trùm đầy đủ 100% mẫu số 78 mục chuyển dịch, có Stable Evidence IDs xác định từ `work/do-an/EVIDENCE_REGISTER.md`, không bỏ sót bất kỳ dữ kiện nào.
- **Mức độ bao phủ bảng biểu và hình ảnh:** Toàn bộ 7 bảng biểu và 11 hình ảnh cũ được phân bổ rõ ràng (MOVE, MERGE, EXPAND, hoặc SUPPORTING), đồng thời quản lý chuẩn xác 14 hình ảnh và 7 bảng biểu đề xuất mới (Bảng 3.5 giữ đúng schema đặc thù 8 thuộc tính Case B; Bảng 3.7 giữ schema riêng 8 tiêu chí tổng hợp 3 trạng thái).
- **Ranh giới kỹ thuật cốt lõi:** 5 tiên đề chân lý, bảo lưu xung đột danh pháp CF-11, giới hạn đo đạc Case B (point-in-time Running, TCP 139 not remeasured, TCP 445 open không có `--reason`), giới hạn Case C (dialect NOT MEASURED, Windows cuối lượt Section 21 dòng 376–384 chứng minh SMB1=True, listeners 139/445, driver srv.sys 16421 UNPATCHED; LanmanServer: Running là truth lock ETM-C-02 kế thừa; đối chiếu theo lineage/tuple), và tính độc lập giữa remote và local được bảo toàn tuyệt đối.
"""

pathlib.Path("work/do-an/CH3_REDESIGN_CONTENT_MIGRATION_MAP_R1.md").write_text(content.strip() + "\n", encoding="utf-8")
print("Successfully generated CH3_REDESIGN_CONTENT_MIGRATION_MAP_R1.md Revision R4")
